### ISSUE TITLE
Help w/YNAB getting "killed" for large combine efforts?

### ISSUE THREAD

**Issue by 7MinSec** [adipinto/yet-another-nessus-parser#2]
Hi there,

I just set ynab.py loose on combining a folder full of .nessus files - specifically 19 files totally 285mb in size.  When I run the ynab job, it seems to grind on it for a long time and eventually exits with "killed."  

Am I just running into an issue where I need to beef up the virtual hardware on this VM (I'll try that tonight), or might it be something else?

Thanks,
Brian

**Comment by TerminalFi** [comment]
Watch your memory for python. I bet it is on a constant climb and then eventually gets killed because of a memory error.

**Comment by 7MinSec** [comment]
Thanks @TheSecEng I ended up having to do more Nessus manipulating than the parser could provide so I checked out this tool and it's really cool (and affordable): https://www.namicsoft.com/
